### ISSUE TITLE
problème de raccourcis claviers (?)

### ISSUE THREAD

**Issue by Refhi** [Refhi/Weda-Helper#141]
https://communaute.weda.fr/t5/user/viewprofilepage/user-id/476

**Comment by Refhi** [comment]
testé sous chrome/windows11, ras (petit délais avant le que le raccourcis soit actif, lié à la fin des mutations + les 300ms de délais)

**Comment by joellebatot** [comment]
hello - suite à mon message sur la commu
je suis sous chrome et sous windows
contenu de la console :

Template.aspx:1 Refused to load the script 'http://secure.weda.fr:12345/ruxitagentjs_ICANVfgqru_10291240606133530.js' because it violates the following Content Security Policy directive: "default-src http://tech.weda.fr http://vidal.weda.fr http://localhost:10002 http://localhost:10003 wss://localhost.icansrv.ovh:9980 wss://message.weda.fr wss://message.weda.fr:3000 wss://localhost.icanopee.net:9980  https://localhost.icanopee.net:9980 wss://*.apizee.com wss://teleconsult.weda.fr https://teleconsult.weda.fr https://campus.vidal.fr wss://local.weda.fr:10004 wss://local.weda.fr:10003 https: data: 'unsafe-inline' 'unsafe-eval' 'self' blob: 'self'". Note that 'script-src-elem' was not explicitly set, so 'default-src' is used as a fallback.

Template.aspx:7 Refused to load the stylesheet 'http://secure.weda.fr:12345/CuteSoft_Client/CuteEditor/Load.ashx?type=style&file=SyntaxHighlighter.css' because it violates the following Content Security Policy directive: "default-src http://tech.weda.fr http://vidal.weda.fr http://localhost:10002 http://localhost:10003 wss://localhost.icansrv.ovh:9980 wss://message.weda.fr wss://message.weda.fr:3000 wss://localhost.icanopee.net:9980  https://localhost.icanopee.net:9980 wss://*.apizee.com wss://teleconsult.weda.fr https://teleconsult.weda.fr https://campus.vidal.fr wss://local.weda.fr:10004 wss://local.weda.fr:10003 https: data: 'unsafe-inline' 'unsafe-eval' 'self' blob: 'self'". Note that 'style-src-elem' was not explicitly set, so 'default-src' is used as a fallback.

breadcrumbs.js:58 EPrescriptionComponent:: ngOnInit
breadcrumbs.js:58 [2024-06-26T09:44:34.603Z] Information: WebSocket connected to wss://local.weda.fr:10003/notifications?instanceId=e5cd721f-d857-48e2-8166-91b5801b3bdb&id=ByFM3JtaIkP89jlDvD0Uxg.
content.js:139 [addTweak] RemoveTitleSuggestions activé
content.js:139 [addTweak] WarpButtons activé
content.js:139 [addTweak] MoveHistoriqueToLeft_Demande activé
content.js:139 [addTweak] autoATCD activé
content.js:139 [addTweak] autoConsentNumPres activé
content.js:139 [addTweak] *NumPres activé
content.js:139 [addTweak] *AutoSelectPrescriptionType activé
keyCommands.js:112 [addShortcuts] ajout des raccourcis sur element #document (https://secure.weda.fr/FolderMedical/DemandeForm.aspx?PatDk=58753759|4252|2486|1&Doc=825423147&DocTyp=3&Eve=556129880&Ori=0&Cre=1&crypt=62-08-C7-FE-E6-BA-06-F8-D4-C7-82-51-A1-70-0D-6A-A4-9F-A8-38-40-D0-9B-B0-33-F6-D2-78-C8-26-74-7F) avec scopeName all et result Object
content.js:299 Window lost focus (blur)
content.js:507 Remove TitleSuggestions started
Consultation.js:446 [autoATCD] bouton atcd détecté
Template.aspx:1 Refused to load the stylesheet 'http://secure.weda.fr:12345/CuteSoft_Client/CuteEditor/Load.ashx?type=style&file=SyntaxHighlighter.css' because it violates the following Content Security Policy directive: "default-src http://tech.weda.fr http://vidal.weda.fr http://localhost:10002 http://localhost:10003 wss://localhost.icansrv.ovh:9980 wss://message.weda.fr wss://message.weda.fr:3000 wss://localhost.icanopee.net:9980  https://localhost.icanopee.net:9980 wss://*.apizee.com wss://teleconsult.weda.fr https://teleconsult.weda.fr https://campus.vidal.fr wss://local.weda.fr:10004 wss://local.weda.fr:10003 https: data: 'unsafe-inline' 'unsafe-eval' 'self' blob: 'self'". Note that 'style-src-elem' was not explicitly set, so 'default-src' is used as a fallback.

VM2338:3 Refused to load the stylesheet 'http://secure.weda.fr:12345/CuteSoft_Client/CuteEditor/Load.ashx?type=style&file=SyntaxHighlighter.css' because it violates the following Content Security Policy directive: "default-src http://tech.weda.fr http://vidal.weda.fr http://localhost:10002 http://localhost:10003 wss://localhost.icansrv.ovh:9980 wss://message.weda.fr wss://message.weda.fr:3000 wss://localhost.icanopee.net:9980  https://localhost.icanopee.net:9980 wss://*.apizee.com wss://teleconsult.weda.fr https://teleconsult.weda.fr https://campus.vidal.fr wss://local.weda.fr:10004 wss://local.weda.fr:10003 https: data: 'unsafe-inline' 'unsafe-eval' 'self' blob: 'self'". Note that 'style-src-elem' was not explicitly set, so 'default-src' is used as a fallback.

Ox9ed @ VM2338:3
Ox85a @ VM2338:3
Ox7d6 @ VM2338:3
CuteEditorImplementation @ VM2338:3
Oxa80 @ Load.ashx?type=scripts&file=Gecko_Loader:3
Oxa7f @ Load.ashx?type=scripts&file=Gecko_Loader:3
Oxa5e @ Load.ashx?type=scripts&file=Gecko_Loader:3
r @ helpers.js:74
T @ zone.js-0.11.4.js:21
r @ helpers.js:74
e.invokeTask @ zone.js-0.11.4.js:6
t.runTask @ zone.js-0.11.4.js:6
t.invokeTask @ zone.js-0.11.4.js:6
p @ zone.js-0.11.4.js:44
h @ zone.js-0.11.4.js:44
Show 2 more frames
Show less
VM2338:3 Window lost focus (blur)
content.js:8 Aucune mutation détectée pendant 300ms, je considère la page comme chargée. Appel du Callback. (ajout raccourcis aux iframes)
keyCommands.js:126 iframe1 <iframe id=​"CE_ContentPlaceHolder1_EditorPrescription_ID_Frame" src=​"/​CuteSoft_Client/​CuteEditor/​Template.aspx?Referrer=http%3a%2f%2fsecure.weda.fr%3a12345%2fFolderMedical%2fDemandeForm.aspx%3fPatDk%3d58753759%7c4252%7c2486%7c1%26Doc%3d825423147%26DocTyp%3d3%26Eve%3d556129880%26Ori%3d0%26Cre%3d1%26crypt%3d62-08-C7-FE-E6-BA-06-F8-D4-C7-82-51-A1-70-0D-6A-A4-9F-A8-38-40-D0-9B-B0-33-F6-D2-78-C8-26-74-7F" frameborder=​"0" spellcheck=​"false" alt=​"EditArea" class=​"CuteEditorFrame CuteEditorFrame" style=​"background-color:​ white;​ border-color:​ rgb(221, 221, 221)​;​ border-width:​ 1px;​ border-style:​ solid;​ height:​ 534px;​ width:​ 100%;​ display:​ block;​" inittime=​"1719395074574">​…​</iframe>​
keyCommands.js:112 [addShortcuts] ajout des raccourcis sur element #document (https://secure.weda.fr/FolderMedical/DemandeForm.aspx?PatDk=58753759|4252|2486|1&Doc=825423147&DocTyp=3&Eve=556129880&Ori=0&Cre=1&crypt=62-08-C7-FE-E6-BA-06-F8-D4-C7-82-51-A1-70-0D-6A-A4-9F-A8-38-40-D0-9B-B0-33-F6-D2-78-C8-26-74-7F) avec scopeName iframe1 et result {defaultShortcuts: {…}}
content.js:304 Window lost focus (hidden)
DemandeForm.aspx:1 Uncaught (in promise) Error: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received


dites moi si une capture d'écran serait plus opportune ou pas ... ?

**Comment by Refhi** [comment]
Non, j'ai déjà pas mal d'infos utiles : notamment il tente bien d'ajouter les raccourcis après le délai prévu.

Est-ce que ton pc est lent à charger les pages de Weda ? Ça pourrait être une piste pour expliquer le problème 🤔 Auquel cas il faudrait qu'on ajoute les raccourcis en deux temps pour tenir compte de ce genre de cas de figure . As-tu l'adsl ou la fibre ?

Serais-tu d'accord pour qu'on organise un rdv téléphonique + teamviewer pour que j'inspecte ton installation ?
Si oui je t'invite à m'envoyer un PM sur le site de la communauté, et je t'appelle quand je peux ? (aucune obligation bien sûr, mais ça permettrait de comprendre plus facilement ce qui coince. Je pense qu'il faut compter 10 minutes environ.)

**Comment by Refhi** [comment]
@Abeldvlpr je pense qu'il s'agit d'un problème qui vient surtout avec l'injection des raccourcis chaotiques au moment du chargement des iframe, dues à l'ouverture de l'iframe des atcds.

Je suis en train de bosser sur ce dernier point, ce qui devrait permettre une injection des raccourcis beaucoup plus précoce et fiable.

https://github.com/Refhi/Weda-Helper/tree/history2leftRefact

**Comment by Refhi** [comment]
a priori réglé par https://github.com/Refhi/Weda-Helper/pull/143

@Abeldvlpr, je peux te laisser tester aussi de ton côté stp ?

Si ça te va, je te propose de merger alpha avec main, de tester quelques jours, puis de pousser la 2.4 tel quel ?

**Comment by Abeldvlpr** [comment]
Je t'ai fait 1 commit car les raccourcis ne fonctionnaient pas sur les pages sans iframe comme la page d'accueil d'un dossier patient et 1 commit pour améliorer un peu l'esthétique de l'iframe historyLeft

**Comment by Abeldvlpr** [comment]
Sinon ca fonctionne niquel, j'ai l'impression que c'est mieux qu'avant même !
En testant un peu, on pourrait même se passer du `afterMutations` mais ca empêche les raccourcis de se charger dans l'iframe historyLeft et ca n'alourdis pas trop le code donc je pense qu'on peut laisser tel quel

**Comment by Refhi** [comment]
> Sinon ca fonctionne niquel, j'ai l'impression que c'est mieux qu'avant même ! En testant un peu, on pourrait même se passer du `afterMutations` mais ca empêche les raccourcis de se charger dans l'iframe historyLeft et ca n'alourdis pas trop le code donc je pense qu'on peut laisser tel quel

ça et ça permet aussi re-injecter les raccourcis quand le DOM a été modifié (par exemple quand on ouvre une fenêtre d'ordo-type)
=> du coup j'ai fait ça :
```function addAllShortcuts() {
    addShortcuts(keyCommands, document, 'all');
    addShortcutsToIframe();
}```
qui est appelé au chargement et avec afterMutation

ça permet de consolider la présence des raccourcis dans tout les scénarios.
Je teste ce midi sur un PC en adsl voire si ça tiens bon.

**Comment by Refhi** [comment]
a priori résolu dans la 2.4, sur une journée de travail je n'ai constaté d'une seule fois où un raccourcis avait sauté dans un iframe, et aucun doublons.
